### ISSUE TITLE
Missing system-config.ts

### ISSUE THREAD

**Issue by gh0st** [Codenator81/ng2do-mean-app#1]
Following from top to bottom I was missing the `system-config.ts` file completely. How'd I miss that? Where was that supposed to be generated or was I supposed to write that myself?

**Comment by gh0st** [comment]
Perhaps there was a version change in angular-cli?

**Comment by Codenator81** [comment]
@gh0st Yes since them change a lot in angular-cli. And them move from SystemJs to Webpack

**Comment by Codenator81** [comment]
My project outdated but idea still the same
