### ISSUE TITLE
AddTodo bug

### ISSUE THREAD

**Issue by JoeMof80** [Codenator81/ng2do-mean-app#5]
`this.todos.push(_todo)` should be `this.todos.push(x)`

Otherwise DeleteTodo will fail because the todo doesn't have an id.

**Comment by Codenator81** [comment]
@JoeMof80
Will update entire app and check for your bug soon...

**Comment by Codenator81** [comment]
Not confirmed. Will close issue. Or give more info how reproduce
@JoeMof80  Update entire app just check if you like
